Setup optimization
appliedzkp/halo2 pull request #53
Opened 2022-03-31 18:41 UTC by spherel

2022-04-01 02:03 UTC, lispc commented
Better give some metric here? For example, old setup code takes XX seconds for degree 18, and new code takes YY seconds.

2022-04-01 04:59 UTC, spherel commented
**[new]**
- test_parameter_serialization, k = 10, **8.06s**, 
- test_commit_lagrange, k = 10, **7.83s**

**[old]**
- test_parameter_serialization, k = 10, **9.99s**
- test_commit_lagrange, k = 10, **9.71s**

**[env]**
- number of thread = 8

2022-04-14 05:09 UTC, spherel commented
<html>
<body>
<p>
Here is the profiling result for some larger k in the same testing environment:

</p>
<!--StartFragment--><google-sheets-html-origin>

k | unsafe_setup (old) | unsafe_setup (new) | improvement | compute monomials (old) | compute monomials (new) | improvement
-- | -- | -- | -- | -- | -- | --
16 | 69.266 s | 56.859 s | 17.91% | 15.77 s | 3.6578 s | 76.81%
18 | 291.14 s | 244.02 s | 16.18% | 62.928 s | 14.965 s | 76.22%
20 | 1233.9 s | 1033.6 s | 16.23% | 252.47 s | 59.618 s | 76.39%

<!--EndFragment-->
</body>
</html>

2022-04-14 10:34 UTC, CPerezz requested changes
Small typo. 

The rest looks good!

2022-04-14 10:34 UTC, CPerezz commented on halo2_proofs/src/poly/commitment.rs
> +use super::super::multicore;
Please, avoid `super::super` patterns. Start from `crate::`.

2022-04-14 18:34 UTC, CPerezz reviewed
Sorry, let me run the tests first. Then we can approve and merge

2022-04-14 18:44 UTC, merged

2022-04-14 19:43 UTC, spherel commented
Great! Thanks!